NDefines.NCountry.CULTURAL_UNION_MIN_DEV = 500
NDefines.NCountry.CULTURAL_UNION_MIN_RANK = 5
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_2 = 25
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_3 = 50
NDefines.NCountry.MIN_DEVELOPMENT_FOR_GOV_RANK_2 = 50
NDefines.NCountry.MIN_DEVELOPMENT_FOR_GOV_RANK_3 = 250
NDefines.Ncountry.PRESTIGE_GAIN_FOR_GOV_RANK_X = 50
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_X = 75
NDefines.NCountry.ADDITIONAL_MIN_DEVELOPMENT_FOR_GOV_RANK_X = 250
NDefines.NCountry.MAX_GOV_RANK = 5
NDefines.NCountry.FEMALE_ADVISOR_CHANCE = 5
NDefines.NCountry.NAT_FOCUS_YEARS = 20
NDefines.NCountry.NAT_FOCUS_YEARS_RANK = 3

NDefines.NMilitary.FORTRESS_COST = 0.75
NDefines.NMilitary.GARRISON_SIZE = 1500

NDefines.NFrontend.CAMERA_LOOKAT_X = 1858.0
NDefines.NFrontend.CAMERA_LOOKAT_Y = 0.0
NDefines.NFrontend.CAMERA_LOOKAT_Z = 1219.0
NDefines.NFrontend.CAMERA_LOOKAT_SETTINGS_X = 1858.0
NDefines.NFrontend.CAMERA_LOOKAT_SETTINGS_Y = 0.0
NDefines.NFrontend.CAMERA_LOOKAT_SETTINGS_Z = 919.0
NDefines.NFrontend.CAMERA_START_X = 1858.0
NDefines.NFrontend.CAMERA_START_Y = 900
NDefines.NFrontend.CAMERA_START_Z = 1100.0
NDefines.NFrontend.CAMERA_END_X = 1858.0
NDefines.NFrontend.CAMERA_END_Y = 800.0
NDefines.NFrontend.CAMERA_END_Z = 1100.0
NDefines.NFrontend.FRONTEND_POS_X = 1858.0
NDefines.NFrontend.FRONTEND_POS_Y = 700.0
NDefines.NFrontend.FRONTEND_POS_Z = 900.0
NDefines.NFrontend.FRONTEND_LOOK_X = 1858.0
NDefines.NFrontend.FRONTEND_LOOK_X = 0.0
NDefines.NFrontend.FRONTEND_LOOK_Z = 919.0

NDefines.NReligion.MAX_CHRISTIAN_RELIGIOUS_CENTERS = 3
NDefines.NReligion.MAX_RELIGIOUS_CENTER_SPREAD_DISTANCE = 225.0
